LRQA-82600
catarineaguiar/liferay-portal pull request #112
Opened 2023-09-05 16:44 UTC by AlexandreMartinsSilva

2023-09-06 16:55 UTC, catarineaguiar requested changes

2023-09-06 16:55 UTC, catarineaguiar commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/MyFormTest.testcase
> +	test CanSubmitaFormWithTwoDifferentLanguages {
Good to see that you used the right way to name the test, just a simple correction is needed on this: `CanSubmitFormWithTwoDifferentLanguages`

2023-09-06 16:55 UTC, catarineaguiar commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/MyFormTest.testcase
> +		Click(
there's a macro that can make this instead of using the Click: `FormViewBuilder.editFieldLabel`

2023-09-06 16:55 UTC, catarineaguiar commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/MyFormTest.testcase
> +		Click(
same as the above comment

2023-09-06 16:55 UTC, catarineaguiar commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/MyFormTest.testcase
> +		Form.submitAgain();
why do we need to submit the form twice?

2023-09-06 16:55 UTC, catarineaguiar commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/MyFormTest.testcase
> +		Form.submitAgain();
same as the above comment

2023-09-06 16:55 UTC, catarineaguiar commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/MyFormTest.testcase
> +		ProductMenu.gotoPortlet(
you can use a faster macro to open forms: `FormsAdmin.openFormsAdmin(siteURLKey = "guest");`

2023-09-08 14:18 UTC, AlexandreMartinsSilva commented
ci:test:sf

2023-09-11 13:50 UTC, catarineaguiar commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/fields/MyFormTest.testcase
> +    test CanSubmitFormWithTwoDifferentLanguages {
@AlexandreMartinsSilva please, use spaces into the macros

2023-09-11 13:50 UTC, catarineaguiar commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/fields/MyFormTest.testcase
> +    test CanSubmitFormWithTwoDifferentLanguages {
put this test in Forms.testcase, please

2023-09-11 13:51 UTC, catarineaguiar approved these changes

2023-09-11 14:06 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d7210e871573904fcf486a55af02f57f5a2d2c74">d7210e871573904fcf486a55af02f57f5a2d2c74</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/AlexandreMartinsSilva/liferay-portal/tree/LRQA-82600">LRQA-82600</a><br/>Branch GIT ID: <a href="https://github.com/AlexandreMartinsSilva/liferay-portal/commit/0c8d4ccb95b4c27860e81927e4fba8d0a0f6830b">0c8d4ccb95b4c27860e81927e4fba8d0a0f6830b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-17.liferay.com/job/test-portal-source-format/6469/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/6469/jenkins-report.html">here</a>.</h5></details></html>

2023-09-11 14:10 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-17.liferay.com/job/test-portal-source-format/6469/">test-portal-source-format#6469</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-source-format/builds/6469/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/catarineaguiar/liferay-portal/pull/112">catarineaguiar#112</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2422100801">[master] ci:test:sf - AlexandreMartinsSilva &gt; catarineaguiar - PR#112 - 2023-09-11[07:02:26]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-17.liferay.com/job/publish-testray-report/3444/">publish-testray-report#3444</a><br/></div></div>

2023-09-11 16:18 UTC, AlexandreMartinsSilva commented
ci:test:sf

2023-09-11 17:04 UTC, catarineaguiar commented
LGTM :smiley_cat:

2023-09-11 17:04 UTC, closed without merging